local base = "ava.plugin-config."
require(base .. "colors")
require(base .. "fugitive")
require(base .. "harpoon")
require(base .. "lsp")
require(base .. "telescope")
require(base .. "treesitter")
require(base .. "undotree")
require(base .. "lualine")
require(base .. "indent-blankline")
require(base .. "comment")
